### ISSUE TITLE
Printing table built using column appending fails in v1.0.0

### ISSUE THREAD

**Issue by asherhoskins** [pri22296/beautifultable#109]
If a table is constructed by appending columns then attempting to print the table fails.

For example:

```python
from beautifultable import BeautifulTable

tbl = BeautifulTable()
tbl.columns.append(["aaa", "bbb", "ccc"], header="One")
tbl.columns.append(["ddd", "eee", "fff"], header="Two")
tbl.columns.append(["ggg", "hhh", "iii"], header="Three")
print(tbl)
```

Produces this error:

```
Traceback (most recent call last):
  File "append_column.py", line 10, in <module>
    print(tbl)
  File "/usr/local/lib/python3.5/dist-packages/beautifultable/beautifultable.py", line 412, in __str__
    for line in self._get_string([], append=False):
  File "/usr/local/lib/python3.5/dist-packages/beautifultable/beautifultable.py", line 1083, in _get_string
    self.rows.insert(0, self.columns.header)
  File "/usr/local/lib/python3.5/dist-packages/beautifultable/helpers.py", line 512, in insert
    self._table._data._insert(index, BTRowData(self._table, row))
AttributeError: 'list' object has no attribute '_insert'
```

Swapping `columns` for `rows` in the above code works (but the table is then rotated by 90 degrees, obv.).

Tested under Python 3.7 on FreeBSD 11.4 and Python 3.5 on Debian 9.13 (Raspberry Pi).

**Comment by asherhoskins** [comment]
If the table is constructed with no headers, by leaving out the `header` option for `append()`, then it works. But headers _cannot_ be added afterwards by setting `tbl.columns.header` or the same error occurs.

**Comment by asherhoskins** [comment]
## Workaround

Writing the columns directly to the `columns[]` array instead of using `columns.append()` seems to work ok, though you do need to set blank row headers for each row of the columns that you wish to add.

```python
from beautifultable import BeautifulTable

tbl = BeautifulTable()

# Initialise the table size by setting the headers.
tbl.columns.header = ["X", "Y", "Z"]
tbl.rows.header = ["", "", ""]

# Directly write each column instead of using append().
tbl.columns[0] = ["aaa", "bbb", "ccc"]
tbl.columns[1] = ["ddd", "eee", "fff"]
tbl.columns[2] = ["ggg", "hhh", "iii"]

print(tbl)
```

This works correctly.

```
+-----+-----+-----+
|  X  |  Y  |  Z  |
+-----+-----+-----+
| aaa | ddd | ggg |
+-----+-----+-----+
| bbb | eee | hhh |
+-----+-----+-----+
| ccc | fff | iii |
+-----+-----+-----+
```

**Comment by pri22296** [comment]
After an initial glance, It seems appending columns with a header, leaves the row headers in a inconsistent state which is leading to this issue. Regarding the workaround, yes that is expected as the table shape is 0x3 prior to not setting the rows.header attribute, directly setting columns array cannot allocate new cells currently, only modify exisitng cells. Setting the header attribute modified the shape of the table to be 3x3 which then allows to set the columns directly.
