### ISSUE TITLE
Suppress deprecation warning (__len__)

### ISSUE THREAD

**Issue by ylieder** [pri22296/beautifultable#114]
Every time I use BeautifulTable I got the following deprecation warning, even if I don't explicitly use the function `__len__` (For example in the minimal tutorial example in the README). Is there a way to suppress this warning? Think it is very useless for the enduser, if the function is not explicitly called.

```
python3.8/site-packages/beautifultable/utils.py:125: FutureWarning: 'BeautifulTable.__len__' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. Use len(BeautifulTable.rows)' instead.
  warnings.warn(message, FutureWarning)
```

**Comment by pri22296** [comment]
@ylieder This should not be happening. I'm not able to replicate this locally. Could you try running the python process with the -W flag or add the following at the top of your minimal code so that we can take a look at the detailed stacktrace.

```python
import warnings
warnings.simplefilter("error")
```

**Comment by ylieder** [comment]
Okay seems to be a problem with PyCharm. I ran the program from within PyCharm with the flag `Run with Python console` set. When adding `warnings.simplefilter("error")` the warning doesn't appear. 
Running the example from the command line works properly.
