### ISSUE TITLE
Markdown external link doesn't work if link is too big.

### ISSUE THREAD

**Issue by ForceConstant** [pri22296/beautifultable#117]
Using this on JupyterLab, and if the url is short it works good, but if it gets too long, the markdown link is not processed.

```
from beautifultable import BeautifulTable
from IPython.display import Markdown


table = BeautifulTable()
table.rows.append(["[Jacob](https://example.com/0123456789/0123456789/01234)", 1, "boy"])
table.rows.append(["[Isabe](https://example.com/0123456789/0123456789/0123)", 1, "gir"])
table.columns.header = ["name", "rank", "gender"]
table.rows.header = ["S1", "S2"]
table.set_style(BeautifulTable.STYLE_MARKDOWN)

Markdown(str(table))
```

![image](https://user-images.githubusercontent.com/26015318/124383403-4247ad00-dc9a-11eb-8f3a-deaf9a087ad9.png)

**Comment by pri22296** [comment]
This is out of scope of this library for now. Any input text in rows are parsed as plain text so things like markdown urls wouldn't be wrapped properly. STYLE_MARKDOWN is more about the styling(characters used to draw the table borders, etc)
