### ISSUE TITLE
Add support to convert table to a list of dict.

### ISSUE THREAD

**Issue by Agent-Hellboy** [pri22296/beautifultable#119]
the `to_dict` or may_be `to_list_of_dict` API can be an useful API. I want to validate the table.
most of package which does schema validation posses an API which takes list of dict and validate it with given schema.
```
+----------+------+--------+
|   name   | rank | gender |
+----------+------+--------+
|  Jacob   |  1   |  boy   |
+----------+------+--------+
| Isabella |  1   |  girl  |
+----------+------+--------+
|  Ethan   |  2   |  boy   |
+----------+------+--------+
|  Sophia  |  2   |  girl  |
+----------+------+--------+
| Michael  |  3   |  boy   |

```
should we converted to something like this 
```
[{'name': 'Jacob', 'rank': 1, 'gender': 'boy'}, {'name': 'Isabella', 'rank': 1, 'gender': 'girl'}, {'name': 'Ethan', 'rank': 2, 'gender': 'boy'}, {'name': 'Sophia', 'rank': 2, 'gender': 'girl'}, {'name': 'Michael', 'rank': 3, 'gender': 'boy'}]
```

**Comment by Agent-Hellboy** [comment]
sorry, I was traveling.
> Now putting that aside, No changing iter would lead to breaking of the current behavior of `list(row)` returning the list of elements.
Yes

> I guess a `asdict`/`todict` method on the row and column classes would be a simple solution which doesn't break anything. So something like `[row.asdict() for row in table.rows]`. Could also add `aslist`/`tolist` for consistency.
Do you want a draft PR for this? I can try if you provide some heads-up to me.
 
> One caveat to note would be that currently headers can have duplicates whereas Dictionaries have unique keys. So the correct behavior in that case needs to be decided. I do thing headers should be ideally be unique but then that would need some implementation changes to handle empty headers. This needs to be decided before we can proceed with a `asdict` method.
I didn't understand it properly `to handle empty headers`. I also think header should be unique.

**Comment by pri22296** [comment]
So currently headers are optional, and if you don't specify header for any of the columns, a header row isn't drawn. So it's possible that if you access the header, you might get None entries which could happen for multiple columns. I guess we could just ignore those in the final dictionary but I'm not sure if that is how it should be.

If we do enforce unique columns, it should be in a way that headers should still be optional. I don't think making it a required field is a good idea.

**Comment by Agent-Hellboy** [comment]
For that case we can raise a warning that `asdict is possible only with column header is not None`

**Comment by pri22296** [comment]
Yeah warning sounds like a good compromise.
We should also raise that warning if header is an empty string because it has the same behaviour as None due to back compatibility reasons.

**Comment by Agent-Hellboy** [comment]
Sure, I have updated the PR. But i am not able to decide `How to integrate asdict with columns?` 
aslist returns 
```
>>> [column.aslist() for column in table.columns]
[['Isabella', 'Jacob'], [1, 1], ['girl', 'boy']]
```

**Comment by Agent-Hellboy** [comment]
Thanks for merging this. Hope, you will make a new release soon.
