### ISSUE TITLE
Need to provide some default styles for easy formatting to standard formats

### ISSUE THREAD

**Issue by pri22296** [pri22296/beautifultable#14]

**Comment by pri22296** [comment]
Primary implementation done in 8366fa9

**Comment by 1605200517** [comment]
if the following goes to this context, do not need a separate ticket: enable setting a style for all columns e.g. make all columns left aligned.

**Comment by pri22296** [comment]
@1605200517 column alignment and other similar properties aren't part of style though. However I like the idea of setting these properties for all columns with a single statement. I suppose we could just have that the following code could be interpreted as

```
table.column_alignments = beautifultable.ALIGN_LEFT
```

setting all columns left aligned. Whereas a particular column will have the same current syntax.

```
table.column_alignments[i] = beautifultable.ALIGN_LEFT
```

Do you mind creating a separate issue for this?
