### ISSUE TITLE
enums in < python 3.4

### ISSUE THREAD

**Issue by IceflowRE** [pri22296/beautifultable#17]
`import enum` [beautifultable/enums.py](https://github.com/pri22296/beautifultable/blob/master/beautifultable/enums.py#L1)
enum exists only in Python 3.4 and onwards. If you want to support versions below (2.7 too) you have to add [enum34](https://pypi.python.org/pypi/enum34) to your requires for the specific versions.

**Comment by pri22296** [comment]
@IceflowRE Thanks for the tip. I did add `enum34` [here](https://github.com/pri22296/beautifultable/blob/faad0e47eaf347eae5c68812a813715426c1ee19/setup.py#L7) . Apparently the uploaded wheel was created with python 3.5 and hence `enum34` was never added to `install_requires`. Taking a look at the wheel documentation, I found [this](https://wheel.readthedocs.io/en/latest/index.html#defining-conditional-dependencies) which should help with this problem. I can't test it currently though.

**Comment by pri22296** [comment]
Fixed in abe1231
