### ISSUE TITLE
Float print formatting broken?

### ISSUE THREAD

**Issue by hoagdoag** [pri22296/beautifultable#21]
This seemed off to me:

python -c "import beautifultable; t = beautifultable.BeautifulTable(); t.append_row(['3.14']); print('%s' % t)"

I get:
+--------------------+
| 3.1400000000000001 |
+--------------------+

when I expect:

+------+
| 3.14 |
+------+

Since I actually specified the row as a string I'm surprised to see was treated as a float (float gives same behavior).

**Comment by pri22296** [comment]
Can you tell me what python version and OS are you using? I couldn't reproduce this issue on my system.
As for the behavior that value being as a string being treated like float, it is intended.

**Comment by hoagdoag** [comment]
Apologies, should have included that in report.

```
bash-4.4$ uname -osr
Linux 4.4.86-11979-g09b49365a3c4 Android
bash-4.4$ python --version
Python 3.6.4
```

I've got a kind of a weird setup by running termux chroot on ChromeOS. I'll try and see if I can repro on ubuntu box later today.

Got it wrt: string treated as float, I guess that makes enough sense if you encourage folks to use the table for data storage/manipulation.

Thanks for the cool lib btw!

**Comment by hoagdoag** [comment]
I can get it to run fine in 3.6.3 and 3.6.4 on Ubuntu LTS 16.04.  So it may just be a weird platform thing (god help me).

3.6.3 below, but 3.6.4 gave exact same.

Will close out.

```
hoagdoag:~$ uname -osr
Linux 4.4.0-1047-aws GNU/Linux
hoagdoag:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
hoagdoag:~$ python3.6 --version
Python 3.6.3
hoagdoag:~$ python3.6 -c "from beautifultable import BeautifulTable; t = BeautifulTable(); t.append_row(['3.14']); print('%s' % t)"
+------+
| 3.14 |
+------+
```

**Comment by pri22296** [comment]
If you wanna investigate more, beautifultable internally rounds off floats to 3 digits(default) using the `round` function. You might wanna check the behavior of `round` function on your platform.
