### ISSUE TITLE
row_count would be very helpful to have

### ISSUE THREAD

**Issue by boyddensmore** [pri22296/beautifultable#24]
First, thanks for the awesome tool!  I'm just getting started with Python, so I'm not quite ready to figure out how to add this myself, but would it be possible to add a row_count method, similar to column_count?

**Comment by pri22296** [comment]
@boyddensmore I'm happy that you find this library awesome. As for your query, you can just use the `len` function to get the row_count similar to as you would find the length of a list in python.
