### ISSUE TITLE
String improperly being converted to float

### ISSUE THREAD

**Issue by adamcasson** [pri22296/beautifultable#25]
I have an element I'm trying to add to my table and it's the string "2e77754" which is an ID number for something. This gets improperly recognized as a float with value 2x10^77754 and thus returns "inf" in my table instead of the string "2e77754".

I think the issue is in `/beautifultable/utils/convert_to_numeric.py`

**Comment by pri22296** [comment]
Thanks for reporting this. The current behaviour is that, if a string can be parsed as a float/int, it will be parsed as a float/int which is handy in many cases but is indeed a problem in cases such as this. I guess I'll add a field to disable this behaviour.

**Comment by pri22296** [comment]
This issue has been fixed in the latest v0.5.1 release
