### ISSUE TITLE
Length of a escape sequence inside a string is taken into account

### ISSUE THREAD

**Issue by 470mr0f1** [pri22296/beautifultable#26]
The length of a escape sequence is taken into account when calculating the col-width.
This is a problem when you want to display a colored string.

For example:

open = \033[1;32open\033[0m

-------------------+
open |
-------------------+

**Comment by 470mr0f1** [comment]
Is there a work around for this? I tried to use padding but the shift still exists.
thanks!

**Comment by pri22296** [comment]
Hi, thanks for reporting this. For now, you could try to encapsulate the string in a custom class with `__len__` defined such that it returns the effective length of the string ignoring escape sequences. Although I'm not sure that would work because I cannot test it currently, but it's worth a try.

**Comment by pri22296** [comment]
This issue is described in #34 and fixed in 5de5af4
