### ISSUE TITLE
Is there a way not to print Column Headers

### ISSUE THREAD

**Issue by RedCarpet** [pri22296/beautifultable#30]
_Hi there - thank you for a great product._
I have table of data that is formatted just perfectly HOWEVER I do **NOT** want the column headers to be printed.
**Is there a way I can stop the column headers from being printed.**

Thank you very much

_PJ_

**Comment by RedCarpet** [comment]
If you were thinking of creating a style for the above situation then something like **STYLE_NONE** would be a good idea. No column headers and no ascii draw characters just plain data.
_Thanx._ HIH
_PJ_

**Comment by pri22296** [comment]
You can specify column_headers as a list of empty strings to disable the printing of headers. As for your suggestion about STYLE_NONE, that seems like a good idea.

**Comment by RedCarpet** [comment]
ok. thank you very much.

**Comment by pri22296** [comment]
`STYLE_NONE` was added in v0.5.2
