### ISSUE TITLE
problem in adding coloration to the table elements

### ISSUE THREAD

**Issue by rjsu26** [pri22296/beautifultable#32]
I tried to use the library colored to add colors to table elements, but when printing, the formatting was rendered to plain text.  I just now saw that Style_NONE was applied. Is the problem due to this command? how can i turn it to manual?

**Comment by pri22296** [comment]
Hi, sorry for the late response. beautifultable currently doesn't support ANSI escape sequences which the colored library uses to add colors. You can track the progress of this feature at #34
