### ISSUE TITLE
Test with python 3.7 on travis

### ISSUE THREAD

**Issue by pri22296** [pri22296/beautifultable#36]
Currently travis seems to have some issue with 3.7(see https://github.com/travis-ci/travis-ci/issues/9815).

**Comment by Anonycoders** [comment]
Hello @pri22296 
We are currently using your library on a production which is out and users have interact with it,
Deprecation Warning is really on their nerve so we want to know is there any estimation for new release?
best regards

**Comment by pri22296** [comment]
@Anonycoders I was planning to release the fix along with some other features in v0.6.0 but it seems the fix was urgent. I have released v0.5.3 which includes the deprecation warning fix. Please note that it is not being tested on travis currently due to the above mentioned issue.
