### ISSUE TITLE
ResourseWarning and UserWarning cant be ingnored.

### ISSUE THREAD

**Issue by zoj613** [pri22296/beautifultable#38]
Hi,
First of all this is a great tool that im planning on using in my own project as a replacement for pandas dataframe. I love that you can index the elements inside a table unlike many other table packages. 

However, everytime I print the a table to the console inside my own project I get the following warnings:
`UserWarning: nperseg = 256 is greater than input length  = 10, using nperseg = 10
  .format(nperseg, input_length))`
`sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=1 mode='w' encoding='utf8'>`

The first warning is a result of my own builtin function and I have successfully filtered out that warning but it always pops back up whenever I use your tool to print a table to the console. Warning number two only appears if I use your tool. I tried suppressing the warning by doing:
`simplefilter('ignore', UserWarning)`
`simplefilter('ignore', ResourceWarning)`

but it just wont go away. DO you have any suggestions on how to deal with this issue?

**Comment by pri22296** [comment]
What is the python version you are using?

**Comment by zoj613** [comment]
> What is the python version you are using?

I am using python v3.6.6.

It seems as though the issue arises because of a progressbar function I created that writes the progress of a function on the console.
`try:
    FILE = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1)
except:
    FILE = open('temp.txt', mode='w', encoding='utf8', buffering=1)

def _progressbar(current, total, elapsed, remain, _fill="█"):
      #some other lines that are irrelevant
      print(text, end="", file=FILE, flush=True)
`
The progressbar is used by a Sampler class that tracks progress of two sampling functions ran simultaneously on two processors using the `loky` package. So I have no way of closing the FILE object  after sampling without running into errors. the `unclosed file` warning was ignore before using your package, now it cant be ignored no matter what I try and is displayed every time I call your package to print a table to the console. Do you have any suggestions to avoid this, the warnings really annoy me and mess up the cleanliness of the table display.
