### ISSUE TITLE
Misaligned when using colored strings via module Blessings

### ISSUE THREAD

**Issue by aniapte** [pri22296/beautifultable#57]
The printed table is misaligned when using colored data via module Blessings.
Here is an example.

```
from beautifultable import BeautifulTable
import blessings

term = blessings.Terminal()

table = BeautifulTable(max_width=120)

table.column_headers = [term.green('Header A'), term.cyan('Header B')]
table.append_row([term.yellow('data'), term.cyan('data')])

print(table)
```
Tested on:
- Python 3.6.7 (default, Oct 22 2018, 11:32:17)

Screenshot of output:
![image](https://user-images.githubusercontent.com/1115421/52619111-e0b6f600-2ec6-11e9-9269-8529709a1b44.png)

**Comment by dinko-pehar** [comment]
I managed to find what causes the problem.

Methods from `blessings.Terminal` return passed strings colored for terminal representation:

```python
>>> import blessings
>>> term = blessings.Terminal()
>>> term.cyan('data')
'\x1b[36mdata\x1b(B\x1b[m'
>>> term.yellow('data')
'\x1b[33mdata\x1b(B\x1b[m'
>>> term.red('data')
'\x1b[31mdata\x1b(B\x1b[m'
>>> term.green('data')
'\x1b[32mdata\x1b(B\x1b[m'
```

but while parsing these strings, `RowData` removes some part of upper mentioned strings, which causes problem with padding when calculating left and right padding.

**Comment by pri22296** [comment]
Thanks for the analysis. It seems the regex in ansi.py module is not enough. It would need to be modified to fix this issue.

**Comment by dinko-pehar** [comment]
I can contribute to project if you like :question:

**Comment by pri22296** [comment]
You're most welcome to submit a PR
