### ISSUE TITLE
Version 0.7 BT: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-138: ordinal not in range(128) 

### ISSUE THREAD

**Issue by taiwotman** [pri22296/beautifultable#58]
I encountered this error using beautifultable v0.70 in python2.7. 

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-138: ordinal not in range(128) `

It occurred during 

`print(table)`

when I used:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
```

or 
```
from __future__ import unicode_literals
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
It printed nothing but noisy results:
`â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
`

**Comment by pri22296** [comment]
Thanks for the report. Can you share a reproducible example for this error?

**Comment by pri22296** [comment]
Python 2.7 is no longer supported
