### ISSUE TITLE
Is it possible to print table row by row from generator without buffering it earlier?

### ISSUE THREAD

**Issue by jacek-jablonski** [pri22296/beautifultable#60]
Hi,
is it possible to print table row by row (f.e. from generator) without buffering it earlier. I have to print quite large amount of data and collecting it takes some time. With this option process of printing large data would look nicer :)

**Comment by pri22296** [comment]
Well you could use multiple tables and print them one after another while styling them as such like they appear to be one single table. You would have to manually set column_widths for all tables to be equal.

I agree that having an option to use a generator to stream data to the table would be a much better option.
