### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by fabaff** [pri22296/beautifultable#86]
On Fedora some tests are failing (https://bugzilla.redhat.com/show_bug.cgi?id=1812435#c1)

Could you please take a look? Thanks in advance.

**Comment by pri22296** [comment]
You need to have [wcwidth](https://pypi.org/project/wcwidth/) library installed to successfully pass all tests.

**Comment by fabaff** [comment]
Thanks.

I was under the impression that nothing is needed as the `tests_require` in the `setup.py` are not mentioning it.
