### ISSUE TITLE
allow zero for padding widths

### ISSUE THREAD

**Issue by furlongm** [pri22296/beautifultable#88]
Sometimes data does not need to be padded at all (e.g. single alphanumerics, or checkmarks).

Currently `set_padding_widths` accepts 0 but this seems to have no effect, and `default_padding` does not accept 0 at all.

Would it be possible to allow for zero padding?

**Comment by pri22296** [comment]
Are you sure about this? I just tired setting it to zero and it worked fine. I'm on 0.8.0 btw.

**Comment by furlongm** [comment]
Ah, you're right. `set_padding_widths` does work with `0`. Could `default_padding` be fixed to allow `0`?
