### ISSUE TITLE
Support row headers

### ISSUE THREAD

**Issue by furlongm** [pri22296/beautifultable#90]
This would be useful where there are too many headers to fit in the terminal, but only a few rows. Something along the lines:

```
print(table.transposed())
```

would be super helpful.

**Comment by pri22296** [comment]
Kind of like instead of columns having titles, rows have titles?

**Comment by furlongm** [comment]
Yes, exactly.

**Comment by furlongm** [comment]
Great, can't wait for this feature! Will v1.0.0 be released on pypi soon?

**Comment by pri22296** [comment]
Yeah. I want to release this weekend but most probably it will be delayed till the next one. Most of the issues after the rewrite have been ironed out. Just need to make some final checks and some documentation updates. The delay is mostly due to the fact that I can only work on weekends on this.
