### ISSUE TITLE
Export/Import from a dataframe

### ISSUE THREAD

**Issue by pri22296** [pri22296/beautifultable#97]

**Comment by Agent-Hellboy** [comment]
Recently my team installed `tabulate` just to get this feature.
I am sharing my approach. if you approve of this, I will raise a PR

There will be 2 APIs(`to_df` and `from_df`) just like `to_csv` and `from_csv` 
```
+-------+------+--------+
| name  | rank | gender |
+-------+------+--------+
| Jacob |  1   |  boy   |
+-------+------+--------+
| Jobi  |  1   |  girl  |
+-------+------+--------+

```
As this table doesn't have row headers we will use the default index for the data frame 
the data frame will look like below 
```
>>> df
    name  rank gender
0  Jacob     1    boy
1   Jobi     1   girl
```
if row headers will be there and we will use that as an Index for data frame rows

`from_df` is straightforward converting data frame to the table 
For that, I am going to use the to_dict API provided for the data frame object.

**Comment by pri22296** [comment]
Yeah this is exactly what I had in mind in how to implement this. Feel free to send a PR.
